// src/routes/(public).tsx
import { createMemo, ParentProps, Show } from "solid-js";
import { Button } from "~components";
import { getOrganizationSettingsFn, getUserFn } from "~lib";

export default function Layout(props: ParentProps) {
  const organization = createMemo(() => getOrganizationSettingsFn());
  const user = createMemo(() => getUserFn());

  return (
    <>
      <header class="absolute inset-x-0 top-0 z-50">
        <nav
          aria-label="Global"
          class="flex items-center justify-between p-6 lg:px-8"
        >
          <div class="flex lg:flex-1">
            <a href="/" class="-m-1.5 p-1.5">
              <span class="sr-only">{organization().name}</span>
              <svg
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
                stroke="currentColor"
                stroke-width="1.75"
                class="h-8 w-auto"
              >
                <circle cx="12" cy="12" r="5" fill="black" />
                <path
                  stroke="currentColor"
                  fill="transparent"
                  d="M 3.3357286,6.9976809 6.3405211,6.3405212 6.9976805,3.3357289 9.9284869,4.2690082 12,1.9953613 14.071513,4.2690081 17.002319,3.3357286 17.659479,6.3405211 20.664271,6.9976805 19.730992,9.9284869 22.004639,12 l -2.273647,2.071513 0.933279,2.930806 -3.004792,0.65716 L 17.00232,20.664271 14.071513,19.730992 12,22.004639 9.9284871,19.730992 6.9976809,20.664271 6.3405212,17.659479 3.3357289,17.00232 4.2690082,14.071513 1.9953613,12 4.2690081,9.9284871 Z"
                />
              </svg>
              {/* <img
                  src=""
                  alt=""
                  class="h-8 w-auto"
                /> */}
            </a>
          </div>
          <div class="flex lg:hidden">
            {/* <Link to="/cart" class="flex items-center gap-1 text-gray-700">
                <span class="text-xs font-semibold">
                  {context().user?.sale?.items.filter(
                    (item) => item.type != "CONVENIENCE FEE",
                  ).length ?? 0}
                </span>
                <svg viewBox="0 0 24 24" class="mr-2 size-6">
                  <path
                    fill="currentColor"
                    d="M17,18A2,2 0 0,1 19,20A2,2 0 0,1 17,22C15.89,22 15,21.1 15,20C15,18.89 15.89,18 17,18M1,2H4.27L5.21,4H20A1,1 0 0,1 21,5C21,5.17 20.95,5.34 20.88,5.5L17.3,11.97C16.96,12.58 16.3,13 15.55,13H8.1L7.2,14.63L7.17,14.75A0.25,0.25 0 0,0 7.42,15H19V17H7C5.89,17 5,16.1 5,15C5,14.65 5.09,14.32 5.24,14.04L6.6,11.59L3,4H1V2M7,18A2,2 0 0,1 9,20A2,2 0 0,1 7,22C5.89,22 5,21.1 5,20C5,18.89 5.89,18 7,18M16,11L18.78,6H6.14L8.5,11H16Z"
                  />
                </svg>
              </Link> */}
            <button
              type="button"
              command="show-modal"
              commandfor="mobile-menu"
              class="-m-2.5 inline-flex cursor-pointer items-center justify-center rounded-md p-2.5 text-gray-700"
            >
              <span class="sr-only">Open main menu</span>
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                data-slot="icon"
                aria-hidden="true"
                class="size-6"
              >
                <path
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>
          </div>
          <div class="hidden lg:flex lg:gap-x-12">
            <a href="/" class="text-sm/6 font-semibold text-gray-900">
              Home
            </a>
            <Show when={organization().hasMembershipTypes}>
              <a
                href="/memberships"
                class="text-sm/6 font-semibold text-gray-900"
              >
                Memberships
              </a>
            </Show>
          </div>
          <div class="hidden lg:flex lg:flex-1 lg:justify-end">
            {/* <Link to="/cart" class="flex items-center gap-1">
                <span class="text-xs font-semibold">
                  {context().user?.sale?.items.filter(
                    (item) => item.type != "CONVENIENCE FEE",
                  ).length ?? 0}
                </span>
                <svg viewBox="0 0 24 24" class="mr-2 size-6 text-gray-700">
                  <path
                    fill="currentColor"
                    d="M17,18A2,2 0 0,1 19,20A2,2 0 0,1 17,22C15.89,22 15,21.1 15,20C15,18.89 15.89,18 17,18M1,2H4.27L5.21,4H20A1,1 0 0,1 21,5C21,5.17 20.95,5.34 20.88,5.5L17.3,11.97C16.96,12.58 16.3,13 15.55,13H8.1L7.2,14.63L7.17,14.75A0.25,0.25 0 0,0 7.42,15H19V17H7C5.89,17 5,16.1 5,15C5,14.65 5.09,14.32 5.24,14.04L6.6,11.59L3,4H1V2M7,18A2,2 0 0,1 9,20A2,2 0 0,1 7,22C5.89,22 5,21.1 5,20C5,18.89 5.89,18 7,18M16,11L18.78,6H6.14L8.5,11H16Z"
                  />
                </svg>
              </Link> */}

            <Show
              when={user()}
              fallback={<Button href="/sign-in" text="Sign In &rarr;" />}
            >
              <a href="/account" class="text-black">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="size-6"
                >
                  <path d="M17.925 20.056a6 6 0 0 0-11.851.001" />
                  <circle cx="12" cy="11" r="4" />
                  <circle cx="12" cy="12" r="10" />
                </svg>
              </a>
            </Show>
          </div>
        </nav>
        <div>
          <dialog id="mobile-menu" class="backdrop:bg-transparent lg:hidden">
            <div tabindex="0" class="fixed inset-0 focus:outline-none">
              <div class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white p-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
                <div class="flex items-center justify-between">
                  <a href="/" class="-m-1.5 p-1.5">
                    <span class="sr-only">{organization().name}</span>
                    <svg
                      viewBox="0 0 24 24"
                      xmlns="http://www.w3.org/2000/svg"
                      stroke="currentColor"
                      stroke-width="1.75"
                      class="h-8 w-auto"
                    >
                      <circle cx="12" cy="12" r="5" fill="black" />
                      <path
                        stroke="currentColor"
                        fill="transparent"
                        d="M 3.3357286,6.9976809 6.3405211,6.3405212 6.9976805,3.3357289 9.9284869,4.2690082 12,1.9953613 14.071513,4.2690081 17.002319,3.3357286 17.659479,6.3405211 20.664271,6.9976805 19.730992,9.9284869 22.004639,12 l -2.273647,2.071513 0.933279,2.930806 -3.004792,0.65716 L 17.00232,20.664271 14.071513,19.730992 12,22.004639 9.9284871,19.730992 6.9976809,20.664271 6.3405212,17.659479 3.3357289,17.00232 4.2690082,14.071513 1.9953613,12 4.2690081,9.9284871 Z"
                      />
                    </svg>
                  </a>
                  <button
                    type="button"
                    command="close"
                    commandfor="mobile-menu"
                    class="-m-2.5 cursor-pointer rounded-md p-2.5 text-gray-700"
                  >
                    <span class="sr-only">Close menu</span>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="1.5"
                      data-slot="icon"
                      aria-hidden="true"
                      class="size-6"
                    >
                      <path
                        d="M6 18 18 6M6 6l12 12"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                    </svg>
                  </button>
                </div>
                <div class="mt-6 flow-root">
                  <div class="-my-6 divide-y divide-gray-500/10">
                    <div class="space-y-2 py-6">
                      <button
                        command="close"
                        commandfor="mobile-menu"
                        class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50"
                      >
                        Home
                      </button>
                      {/* <Show when={context().settings.hasMembershipTypes}>
                          <button
                            command="close"
                            commandfor="mobile-menu"
                            onClick={() => {
                              navigate({ to: "/memberships" });
                            }}
                            class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50"
                          >
                            Memberships
                          </button>
                        </Show> */}
                    </div>
                    <div class="py-6">
                      <Show
                        when={user}
                        fallback={
                          <Button href="/sign-in" text="Sign In &rarr;" />
                        }
                      >
                        <Button href="/account" text="My Account &rarr;" />
                      </Show>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </dialog>
        </div>
      </header>
      <div class="bg-white">{props.children}</div>
      <footer class="bg-white">
        <div class="mx-auto max-w-7xl px-6 py-16 lg:px-8">
          <div class="xl:grid xl:grid-cols-3 xl:gap-8">
            <div class="space-y-4">
              <div class="flex items-center gap-2">
                <svg
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                  stroke="currentColor"
                  stroke-width="1.75"
                  class="h-8 w-auto"
                >
                  <circle cx="12" cy="12" r="5" fill="black" />
                  <path
                    stroke="currentColor"
                    fill="transparent"
                    d="M 3.3357286,6.9976809 6.3405211,6.3405212 6.9976805,3.3357289 9.9284869,4.2690082 12,1.9953613 14.071513,4.2690081 17.002319,3.3357286 17.659479,6.3405211 20.664271,6.9976805 19.730992,9.9284869 22.004639,12 l -2.273647,2.071513 0.933279,2.930806 -3.004792,0.65716 L 17.00232,20.664271 14.071513,19.730992 12,22.004639 9.9284871,19.730992 6.9976809,20.664271 6.3405212,17.659479 3.3357289,17.00232 4.2690082,14.071513 1.9953613,12 4.2690081,9.9284871 Z"
                  />
                </svg>
                <span class="text-lg font-semibold text-gray-900">
                  {organization().name}
                </span>
              </div>

              <p class="max-w-md text-sm text-gray-600">
                We connecting our community to the wonders of science, space,
                and discovery through experiences that educate, entertain, and
                inspire.
              </p>
            </div>

            <div class="mt-12 grid grid-cols-2 gap-8 xl:col-span-2 xl:mt-0">
              <div class="md:grid md:grid-cols-2 md:gap-8">
                <div>
                  <h3 class="text-sm font-semibold text-gray-900">
                    For the General Public
                  </h3>
                  <ul class="mt-4 space-y-3">
                    <li>
                      <a
                        href="/"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Upcoming Events
                      </a>
                    </li>
                    <li>
                      <a
                        href="/"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Memberships
                      </a>
                    </li>
                  </ul>
                </div>
                <div class="mt-10 md:mt-0">
                  <h3 class="text-sm font-semibold text-gray-900">
                    For Groups
                  </h3>
                  <ul class="mt-4 space-y-3">
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        School Groups
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Civic Groups
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div class="md:grid md:grid-cols-2 md:gap-8">
                <div>
                  <h3 class="text-sm font-semibold text-gray-900">Other</h3>
                  <ul class="mt-4 space-y-3">
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Events Calendar
                      </a>
                    </li>
                  </ul>
                </div>
                <div class="mt-10 md:mt-0">
                  <h3 class="text-sm font-semibold text-gray-900">About</h3>
                  <ul class="mt-4 space-y-3">
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Privacy
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Terms
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Cookies
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        class="text-sm text-gray-600 hover:text-gray-900"
                      >
                        Licenses
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="mt-16 border-t border-gray-200 pt-8">
            <p class="text-sm text-gray-500">
              &copy; {new Date().getFullYear()} {organization().name}. All
              rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </>
  );
}

// ui/apps/web/src/routes/(public)/+page.svelte
<script lang="ts">
	let { data } = $props();
</script>

<svelte:head>
	<title>{data.settings?.organization.name} Home | Astral</title>
</svelte:head>

<div class="border-b">
	<div class="flex h-16 items-center px-4">
		<nav class="flex items-center space-x-4 lg:mx-3 lg:space-x-6">
			<h1 class="hidden text-xl font-bold lg:block">{data.settings?.organization.name}</h1>
			<a
				class="text-sm font-medium transition-colors hover:text-primary"
				href="/examples/dashboard"
			>
				Home
			</a>
			<a
				class="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
				href="/examples/dashboard">Events</a
			><a
				class="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
				href="/examples/dashboard">Products</a
			>
		</nav>
		<div class="ml-auto flex items-center space-x-4">
			<div class="hidden lg:block">
				<input
					class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:w-[100px] lg:w-[300px]"
					placeholder="Search..."
					type="search"
				/>
			</div>
			{#if data.account === undefined}
				<a
					href="/login"
					class="inline-flex h-9 items-center justify-center whitespace-nowrap rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
				>
					Login
				</a>
			{:else}
				<button
					class="inline-flex h-9 w-9 items-center justify-center whitespace-nowrap rounded-full bg-secondary text-sm font-medium text-secondary-foreground shadow-sm transition-colors hover:bg-secondary/80 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
					type="button"
					id="radix-:R1db9uuuuu6ja:"
					aria-haspopup="menu"
					aria-expanded="false"
					data-state="closed"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="lucide lucide-circle-user h-5 w-5"
						><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="10" r="3"></circle><path
							d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662"
						></path></svg
					><span class="sr-only">Toggle user menu</span></button
				>
			{/if}
		</div>
	</div>
</div>

<section class="grid gap-3 p-6">
	<h2 class="text-2xl font-semibold tracking-tight">Upcoming Events ({data.events.length})</h2>
	<p class="text-sm text-muted-foreground">Our next scheduled public events.</p>
	<div role="none" class="my-4 h-[1px] w-full shrink-0 bg-border"></div>
	<div class="flex gap-3 overflow-x-auto py-3">
		{#each data.events as event}
			<a href={`/events/${event.id}`} class="w-[250px] flex-none space-y-3">
				<span data-state="closed">
					<div class="overflow-hidden rounded-md">
						<img
							alt="React Rendezvous"
							loading="lazy"
							width="250"
							height="330"
							decoding="async"
							data-nimg="1"
							class="aspect-[3/4] h-auto w-auto object-cover transition-all hover:scale-105"
							style="color: transparent;"
							src={event.show.cover}
						/>
					</div>
				</span>
				<div class="space-y-1 text-sm">
					<h3 class="truncate font-medium leading-none">{event.show.name}</h3>
					<p class="text-xs text-muted-foreground">
						{event.show.type?.name} &middot; {event.type.name}
					</p>
				</div>
			</a>
		{/each}
	</div>
	<br />
	<h2 class="text-2xl font-semibold tracking-tight">Products ({data.products?.length})</h2>
	<p class="text-sm text-muted-foreground">Gifts, souvenirs and other items you can buy from us.</p>
	<div role="none" class="my-4 h-[1px] w-full shrink-0 bg-border"></div>
	<div class="flex gap-3 overflow-x-auto py-3">
		{#each data.products as product}
			<a href={`/products/${product.id}`} class="w-[150px] flex-none space-y-3">
				<span data-state="closed">
					<div class="overflow-hidden rounded-md">
						<img
							alt="Thinking Components"
							loading="lazy"
							width="150"
							height="150"
							decoding="async"
							data-nimg="1"
							class="aspect-square h-auto w-auto object-cover transition-all hover:scale-105"
							style="color: transparent;"
							src={product.cover}
						/>
					</div>
				</span>
				<div class="space-y-1 text-sm">
					<h3 class="font-medium leading-none">{product.name}</h3>
					<p class="text-xs text-muted-foreground">${product.price}</p>
				</div>
			</a>
		{/each}
	</div>
</section>
